### ISSUE TITLE
Merge actual state of project in Master branch

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/python-support#20]
I think it no longer makes sense to work at the resource branch.
In my opinion, we should migrate the current state of this repository to master to work in the same pattern as other projects.

**Comment by sleipnir** [comment]
@marcellanz @chomnoue  WDYT?

**Comment by marcellanz** [comment]
@sleipnir I agree. I have that on my list and just did not have time yet.
I will re-phrase the README also, so that its clear what state the repository is on.
